### ISSUE TITLE
Compilation Error

### ISSUE THREAD

**Issue by swartzd** [42ity/fty-rest#201]
Debian 8
GNU Make 4.1
gcc (Debian 6.3.0-12) 6.3.0 20170406

```
In file included from src/shared/utils_web.cc:31:0:
/opt/FTY/fty-rest/src/include/utils_web.h: In function ‘void utils::config::assert_key(const string&)’:
src/shared/utils_web.cc:283:9:   in constexpr expansion of ‘_die_idx<13ul>(((const char*)"request-param-bad"))’
/opt/FTY/fty-rest/src/include/utils_web.h:96:89:   in constexpr expansion of ‘_die_idx<12ul>(key)’
/opt/FTY/fty-rest/src/include/utils_web.h:96:31: error: ‘(((const char*)"not-found") != ((const char*)"request-param-bad"))’ is not a constant expression
     return (_errors.at(N).key == key || _errors.at(N).message == key) ? N: _die_idx<N-1>(key);
             ~~~~~~~~~~~~~~~~~~^~~~~~
/opt/FTY/fty-rest/src/include/utils_web.h: In function ‘void utils::config::assert_value(const string&, const string&)’:
src/shared/utils_web.cc:295:9:   in constexpr expansion of ‘_die_idx<13ul>(((const char*)"request-param-bad"))’
/opt/FTY/fty-rest/src/include/utils_web.h:96:89:   in constexpr expansion of ‘_die_idx<12ul>(key)’
/opt/FTY/fty-rest/src/include/utils_web.h:96:31: error: ‘(((const char*)"not-found") != ((const char*)"request-param-bad"))’ is not a constant expression
/opt/FTY/fty-rest/src/include/utils_web.h: In function ‘void utils::config::json2zpl(std::map<std::__cxx11::basic_string<char>, _zconfig_t*>&, const cxxtools::SerializationInfo&, std::lock_guard<std::mutex>&)’:
src/shared/utils_web.cc:309:9:   in constexpr expansion of ‘_die_idx<13ul>(((const char*)"bad-request-document"))’
/opt/FTY/fty-rest/src/include/utils_web.h:96:89:   in constexpr expansion of ‘_die_idx<12ul>(key)’
/opt/FTY/fty-rest/src/include/utils_web.h:96:31: error: ‘(((const char*)"not-found") != ((const char*)"bad-request-document"))’ is not a constant expression
src/shared/utils_web.cc:341:17:   in constexpr expansion of ‘_die_idx<13ul>(((const char*)"bad-request-document"))’
/opt/FTY/fty-rest/src/include/utils_web.h:96:89:   in constexpr expansion of ‘_die_idx<12ul>(key)’
/opt/FTY/fty-rest/src/include/utils_web.h:96:31: error: ‘(((const char*)"not-found") != ((const char*)"bad-request-document"))’ is not a constant expression
src/shared/utils_web.cc:356:17:   in constexpr expansion of ‘_die_idx<13ul>(((const char*)"internal-error"))’
/opt/FTY/fty-rest/src/include/utils_web.h:96:89:   in constexpr expansion of ‘_die_idx<12ul>(key)’
/opt/FTY/fty-rest/src/include/utils_web.h:96:31: error: ‘(((const char*)"not-found") != ((const char*)"internal-error"))’ is not a constant expression
src/shared/utils_web.cc:394:13:   in constexpr expansion of ‘_die_idx<13ul>(((const char*)"bad-request-document"))’
/opt/FTY/fty-rest/src/include/utils_web.h:96:89:   in constexpr expansion of ‘_die_idx<12ul>(key)’
/opt/FTY/fty-rest/src/include/utils_web.h:96:31: error: ‘(((const char*)"not-found") != ((const char*)"bad-request-document"))’ is not a constant expression
Makefile:3146: recipe for target 'src/shared/libpriv_utils_la-utils_web.lo' failed
make[1]: *** [src/shared/libpriv_utils_la-utils_web.lo] Error 1
make[1]: Leaving directory '/opt/FTY/fty-rest'
Makefile:1655: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by jimklimov** [comment]
Interesting - on the face value, it rightfully complains about comparing pointers to static strings, which is wrong. I think it should have been comparing C++ String's.

Maybe this is a quirk of gcc6 though - they did make many changes, in ABI and deeper inspection for warnings and stuff. May also be a bug, that for some reason one comparator is used instead of another. In particular, the ABI differences may mean it does not play well with installed C++ packages built by older GCC, such as tntnet and cxxtools among our dependencies.

It may also be requiring use of newer standards, like gnu++14 by default, while our code mostly adheres to older ones and works with GCC-4.6.x on Travis CI (with a few exceptions where c++11 and compilation with GCC-4.8.x or newer is explicitly needed - so newer "dist" and/or "docker" setups are used in Travis).

Does such error also pop up trying to `make world` in a checkout of https://github.com/42ity/FTY repo with your setup?

While I am not sure the team would commit via dayjob to actively support more environments than currently sufficient for the product, they should certainly not object to accepting fixes that improve portability - or fix the actual bugs discovered thanks to alternative compilers and tools.

**Comment by vyskocilm** [comment]
Hi @swartzd,

thanks for the issue. We know that in gcc 5+ rules for constexpr are strictier in a way it broke our code. I am working on a port of SW to Ubuntu 16.04 to support other project's development and it will touch this as well. I'll close it when PR will be merged.

**Comment by FrancoisRegisDegott-eaton** [comment]
deprecated
